baseURL: "https://dennispater.com"
title: Dennis Pater
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: nl

languages:
  nl:
    languageName: "🇳🇱 Nederlands"
    langageAltTitle: Nederlands
    languageCode: "nl-NL"
    subtitle: "Mijn Persoonlijke portfolio site!"
    weight: 0
    taxonomies:
      category: categorie
      tags: labels
    profileMode:
      enabled: true # needs to be explicitly set
      title: Hoi, welkom!
      subtitle: "Dit is de website van Dennis Pater."
      imageUrl: "/dennis.jpg"
      imageWidth: 120
      imageHeight: 120
      imageTitle: Dennis Pater in Noorwegen
      buttons:
        - name: Over mij
          url: about
        - name: Blog
          url: blog
    menu:
      main:
          - name: blog
            url: /blog/
            weight: 5
          - name: categorie
            url: /categorie/
            weight: 10
          - name: Over mij
            url: /about/
            weight: 90

  en:
    languageName: "🇬🇧 English"
    langageAltTitle: English
    languageCode: "en-US"
    title: Hi, welcome!
    subtitle: "This is the website from Dennis Pater."
    weight: 1
    taxonomies:
      category: category
      tags: tags
    profileMode:
      enabled: true # needs to be explicitly set
      title: Dennis Pater 
      subtitle: "My personal portfolio site!"
      imageUrl: "/dennis.jpg"
      imageWidth: 120
      imageHeight: 120
      imageTitle: Dennis Pater in Norway
      buttons:
        - name: About me
          url: about
        - name: Blog
          url: blog
    menu:
      main:
          - name: blog
            url: /blog/
            weight: 5
          - name: category
            url: /category/
            weight: 10
          - name: About me
            url: /about/
            weight: 90

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Dennis Pater
  description: "Persoonlijke portfolio"
  keywords: [Blog, Portfolio]
  author: Dennis Pater
  # author: ["Me", "You"] # multiple authors
  images: ["/dennis.jpg"]
  DateFormat: "2 januari 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: true
  displayFullLangName: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["facebook", "linkedin", "twitter", "whatsapp"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/dpater1986"

        #analytics:
        #google:
        #SiteVerificationTag: "XYZabc"
        #bing:
        #SiteVerificationTag: "XYZabc"
        #yandex:
        #SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
