title: "Gallery"
languageCode: "nl-nl"
copyright: "© Dennis Pater"
disableKinds: ["taxonomy", "term"]
defaultContentLanguage: "nl"
enableRobotsTXT: false
timeZone: "Europe/Amsterdam"

params:
  title: "Dennis Pater"
  description: "Welkom in Drenthe!"
  defaultTheme: "dark"

author:
  name: "Dennis Pater"

outputs:
  page: ["HTML"]
  home: ["HTML", "RSS"]
  section: ["HTML"]

imaging:
  resampleFilter: "CatmullRom"
  quality: 75
  exif:
    disableDate: false
    disableLatLong: false
    includeFields: "ImageDescription"

menu:
  footer:
    name: "Dennis Pater"
    url: "https://dennispater.com/"
    weight: 3