title = "Gallery"
languageCode = "nl-nl"
copyright = "© Dennis Pater"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "nl"
enableRobotsTXT = false
timeZone = "Europe/Amsterdam"

[params]
  title = "Dennis Pater"
  description = "Welkom in Drenthe!"
  defaultTheme = "dark"

[author]
  name = "Dennis Pater"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = false
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
  name = "Dennis Pater"
  url = "https://dennispater.com/"
  weight = 3